# C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y

# increase the stack size of the main thread
CONFIG_MAIN_STACK_SIZE=2048

# we use zpp_lib
CONFIG_USE_ZPP_LIB=y

# HW
CONFIG_GPIO=y
