name: Test AES workspace 

on:
    # push:               # Run the workflow on every push to any branch
    # pull_request:       # Run the workflow on every pull request
    workflow_dispatch:  # Allow manual triggering from the GitHub Actions UI
    
jobs:
  build-apps:
    uses: AdvEmbSof/common-workflows/.github/workflows/build-zephyr-apps.yml@main
    secrets:
      personal_access_token: ${{ secrets.ADVEMBSOF_2025_2026 }}
    with:
      boards: '["nrf5340dk/nrf5340/cpuapp","qemu_x86"]' # JSON array of target boards for the build
      applications: '["blinky","sensor-bme280"]' # JSON array of applications to build
   
  test-apps:
    uses: AdvEmbSof/common-workflows/.github/workflows/twister-tests.yml@main
    secrets:
      personal_access_token: ${{ secrets.ADVEMBSOF_2025_2026 }}
    with:
      test-on: '["bike_computer"]' # JSON array of applications to run twister tests
    permissions:
      checks: write
      pull-requests: write
      contents: read
    
